name: Testing

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    strategy:
      matrix:
        language: ['typeScript']
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: npm i

      - name: Run Eslint
        run: npm run eslint
        
      - name: Run tests
        run: npm test
        
      - name: Run tests coverage
        run: npm test -- --coverage

      - name: Monitor coverage
        id: coverage-monitor-clover
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: ".coverage/clover.xml"
          comment_context: "Coverage from clover"

      - name: Monitor coverage
        id: coverage-monitor-json
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: ".coverage/coverage-summary.json"
          comment_context: "Coverage from json-summary"
          check: false
